### ISSUE TITLE
Padding issues

### ISSUE THREAD

**Issue by neocotic** [neocotic/qr.js#2]
The whitespace padding needs to be much more consistent as it currently varies depending on the size and doesn't fill the dimensions well enough.

**Comment by andrewagain** [comment]
Looks like this is still an issue in the latest version: 4.0.2

![screen shot 2018-01-16 at 12 52 00 pm](https://user-images.githubusercontent.com/597825/35011744-1de81512-fabc-11e7-8991-1a5d276d0bf9.png)

![screen shot 2018-01-16 at 12 51 54 pm](https://user-images.githubusercontent.com/597825/35011749-2253905e-fabc-11e7-88f0-cee1f5fef081.png)

My options:

```
    var qr = new QRious({
      element: canvasElement,
      level: "L",
      padding: 0,
      size: 100,
      value: "meow"
    });
```

**Comment by pcooperuk** [comment]
Hi,
Even thought this issue is closed, it's still happens with the latest version and its not a nice UI experience.
As wanted to use the library, I have made a tweak to improve this just one line change if you want to include into the official version.

just replace line 404 in qrious.js 

from:
var offset = this.getOffset(frame);

to:
var offset=parseInt((this.element.width-(frame.width*moduleSize))/2);

tested across a variety of sizes and content

**Comment by zcqno1** [comment]
I guess it maybe because the QR code's minimal unit's size could not be bigger, otherwise, the total size would be larger than the expected size. Using the scale method may force the size to cover.
By the way, set a higher level would make it better, but also more complex.
Maybe the document should note the padding issue.
